# Generated by Django 5.1.15 on 2026-01-12 12:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje'), (2, 'Fijo')])),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')])),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('usos_maximos', models.IntegerField()),
                ('usos_actuales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Usado'), (3, 'Reacondicionado')])),
                ('nombre', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_piezas/')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'administrador'), (2, 'empleado'), (3, 'cliente')], default=3)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignado', models.DateField()),
                ('veces_usado', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='proyecto.cliente')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='proyecto.descuento')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobada'), (3, 'Rechazada')])),
                ('fecha_solicitud', models.DateField()),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('cantidad_devuelta', models.IntegerField()),
                ('monto_reembolso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='proyecto.cliente')),
                ('linea_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='proyecto.lineapedido')),
            ],
        ),
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_deseos', to='proyecto.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_metodo', models.PositiveSmallIntegerField(choices=[(1, 'Tarjeta'), (2, 'Cuenta Bancaria'), (3, 'Billetera Digital')])),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('fecha_agregado', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='proyecto.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=255)),
                ('banco', models.CharField(max_length=100)),
                ('moneda', models.CharField(max_length=10)),
                ('metodo_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='proyecto.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='BilleteraDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.PositiveSmallIntegerField(choices=[(1, 'PayPal'), (2, 'Stripe'), (3, 'Google Pay')])),
                ('email', models.EmailField(max_length=254)),
                ('metodo_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera_digital', to='proyecto.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado'), (3, 'Enviado'), (4, 'Entregado'), (5, 'Cancelado')])),
                ('fecha_pedido', models.DateField()),
                ('direccion_envio', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to='proyecto.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'PENDIENTE'), (2, 'COMPLETADO'), (3, 'FALLIDO')])),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_transaccion', models.CharField(max_length=100)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='proyecto.metodopago')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='proyecto.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='proyecto.pedido'),
        ),
        migrations.CreateModel(
            name='ListaDeseosPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateField()),
                ('lista_deseos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyecto.listadeseos')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_deseos', to='proyecto.pieza')),
            ],
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='proyecto.pieza'),
        ),
        migrations.CreateModel(
            name='ImagenPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_piezas/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='proyecto.pieza')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.PositiveSmallIntegerField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'American Express')])),
                ('num_tarjeta_encriptado', models.CharField(max_length=255)),
                ('propietario', models.CharField(max_length=100)),
                ('fecha_caducidad', models.CharField(max_length=7)),
                ('moneda', models.CharField(max_length=10)),
                ('metodo_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to='proyecto.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('fecha_valoracion', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='proyecto.cliente')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='proyecto.pieza')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField()),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_vendedor', to='proyecto.vendedor'),
        ),
    ]
