# Generated by Django 5.1.14 on 2025-11-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('N', 'Nueva'), ('R', 'Recuperada'), ('REC', 'Reconstruida')], max_length=3)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.FloatField(default=1.0)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
