# Generated by Django 5.1.14 on 2025-11-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_caducidad',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
    ]
