# Generated by Django 5.1.15 on 2026-01-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen_categoria', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pieza',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_piezas', to='proyecto.categoriapieza'),
        ),
    ]
