# Generated by Django 5.1.14 on 2025-11-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_usuario_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billeteradigital',
            name='proveedor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PayPal'), (2, 'Stripe'), (3, 'Google Pay')]),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')]),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje'), (2, 'Fijo')]),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobada'), (3, 'Rechazada')]),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo_metodo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tarjeta'), (2, 'Cuenta Bancaria'), (3, 'Billetera Digital')]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PENDIENTE'), (2, 'COMPLETADO'), (3, 'FALLIDO')]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado'), (3, 'Enviado'), (4, 'Entregado'), (5, 'Cancelado')]),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Usado'), (3, 'Reacondicionado')]),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo_tarjeta',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'American Express')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administrador'), (2, 'empleado'), (3, 'cliente')]),
        ),
    ]
