# Generated by Django 5.1.15 on 2026-01-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_lineapedido_estado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listadeseospieza',
            constraint=models.UniqueConstraint(fields=('lista_deseos', 'pieza'), name='unique_pieza_por_lista'),
        ),
    ]
