# Generated by Django 5.1.14 on 2025-12-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_billeteradigital_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administrador'), (2, 'empleado'), (3, 'cliente')], default=3),
        ),
    ]
