# Generated by Django 5.1.15 on 2025-12-30 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_piezas/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='proyecto.pieza')),
            ],
        ),
    ]
