# Generated by Django 5.1.15 on 2026-02-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_listadeseospieza_unique_pieza_por_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado'), (3, 'Enviado'), (4, 'Entregado'), (5, 'Cancelado'), (6, 'Carrito')]),
        ),
    ]
