# Generated by Django 5.1.15 on 2026-02-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='proyecto.metodopago'),
        ),
        migrations.CreateModel(
            name='PagoPayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(max_length=100, unique=True)),
                ('paypal_capture_id', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Creado'), (2, 'Aprobado'), (3, 'Capturado'), (4, 'Fallido'), (5, 'Cancelado')], default=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('respuesta_paypal', models.JSONField(blank=True, null=True)),
                ('pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_paypal', to='proyecto.pago')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_paypal', to='proyecto.pedido')),
            ],
        ),
    ]
