# Generated by Django 5.1.15 on 2025-12-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_imagenpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_piezas/'),
        ),
    ]
