# Generated by Django 5.1.15 on 2026-02-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_pago_metodo_pago_pagopaypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
