# Generated by Django 5.1.15 on 2026-03-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_valoracion_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='foto_perfil_vendedor',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil_vendedor/'),
        ),
    ]
