# Generated by Django 5.1.15 on 2026-03-19 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_vendedor_foto_perfil_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_vendedor', to='proyecto.vendedor'),
        ),
    ]
