# Generated by Django 5.1.15 on 2026-04-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_eventocliente'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventocliente',
            new_name='evento_clie_nombre__955212_idx',
            old_name='evento_clie_nombre__2aa007_idx',
        ),
        migrations.RenameIndex(
            model_name='eventocliente',
            new_name='evento_clie_fecha_e_fb9532_idx',
            old_name='evento_clie_fecha_e_9c11dc_idx',
        ),
        migrations.RenameIndex(
            model_name='eventocliente',
            new_name='evento_clie_cliente_0a5abf_idx',
            old_name='evento_clie_cliente_2c9fb0_idx',
        ),
    ]
