services:
  postgres:
    image: postgres:16  #Utiliza la versión 16 de PostgreSQL
    container_name: tienda_db # Nombre del contenedor
    environment:
      POSTGRES_DB: tienda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" #conexion de mi ordenador al contenedor
    volumes:
      - postgres_data:/var/lib/postgresql/data #aqui guardamos los datos de la base de datos 

  #Servicio para levantar la aplicación Django utilizando Gunicorn y Nginx
  # web:
  #   build: .
  #   container_name: tienda_web
  #   command: > sh -c "python manage.py migrate && gunicorn proyecto.wsgi:application --bind 0.0.0.0:8000"
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8000:8000" 
 


volumes:
  postgres_data:
