# Nginx configuration for Django + Gunicorn
#server {
#    listen 80;
#    server_name _;
#
#    location /static/ {
#        alias /app/static/;
#    }
#
#    location /media/ {
#        alias /app/media/;
#    }
#
#    location / {
#        proxy_pass http://web:8000;
#        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#        proxy_set_header X-Forwarded-Proto $scheme;
#    }
#}

server {
    listen 80;
    server_name _;

    # --- Frontend Vue ---
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # --- API Django ---
    location /api/ {
        proxy_pass http://web:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- Static ---
    location /static/ {
        alias /app/static/;
    }

    # --- Media ---
    location /media/ {
        alias /app/media/;
    }
}
