"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rneen%%$g57ob1h#ll+t%4r+yahrlyuaw@8fxuvc!@5^e7hf$q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = ['0.0.0.0', '127.0.0.1', 'localhost', '34.238.73.57','23.23.32.46', 'ec2-44-221-235-149.compute-1.amazonaws.com', '44.221.235.149', 
                 'proyectointegrado-production-ec47.up.railway.app']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'proyecto',
    'rest_framework',
    'corsheaders',
    'django_filters',

    #Para la lógica del logout con JWT
    'rest_framework_simplejwt', 
    'rest_framework_simplejwt.token_blacklist',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # Debe estar ANTES de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'

]

# CAMBIO 1: Configuración de CORS y CSRF (Los permisos para Vue)
CORS_ALLOWED_ORIGINS = [
    'http://3.225.154.212',  # Frontend
    'http://44.221.235.149', # Backend (por si accedes desde navegador a la API)
    'http://localhost:8080',
    'http://127.0.0.1:8081',
    'https://proyectointegrado-production-ec47.up.railway.app'
]

# ¡ESTO ES VITAL! Permite que las cookies viajen entre el puertos
CORS_ALLOW_CREDENTIALS = True


# Le decimos a Django que confíe en Vue para enviar formularios
CSRF_TRUSTED_ORIGINS = [
    #'http://23.23.32.46',
    #'http://34.238.73.57',
    'http://localhost:8080',
    'http://127.0.0.1:8081',
    'proyectointegrado-production-ec47.up.railway.app'
]



ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

#Nueva configuración para PostgreSQL
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('POSTGRES_NAME'),
#         'USER': os.getenv('POSTGRES_USER'),
#         'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
#         'HOST': os.getenv('POSTGRES_HOST'),
#         'PORT': os.getenv('POSTGRES_PORT'), 
#     }
# }


#Para deploy en Railway
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# URL pública para acceder (lo que se ve en el navegador)
MEDIA_URL = '/media/'

# Ruta física en tu disco duro donde se guardan los archivos
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'proyecto.Usuario' # Indica que voy a sobreescribir user model al usuario que tengo en mi modelo

# CAMBIO 3: Cambiar el motor de autenticación de DRF
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
   
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',

    ),
}


# ============================================================
# CONFIGURACIÓN DE PAYPAL
# ============================================================
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET')
PAYPAL_MODE = os.getenv('PAYPAL_MODE', 'sandbox')  # 'sandbox' 

# URLs de retorno después del pago (Para VUE)
PAYPAL_RETURN_URL = os.getenv('PAYPAL_RETURN_URL', 'http://localhost:8080/pago/exito')
PAYPAL_CANCEL_URL = os.getenv('PAYPAL_CANCEL_URL', 'http://localhost:8080/pago/cancelado')

#PAYPAL_RETURN_URL = os.getenv('PAYPAL_RETURN_URL', 'http://3.225.154.212/pago/exito')
#PAYPAL_CANCEL_URL = os.getenv('PAYPAL_CANCEL_URL', 'http://3.225.154.212/pago/cancelado')



# ============================================================
# CONFIGURACIÓN DE EMAIL (Para recuperación de contraseña)
# ============================================================

# Email de envío por defecto
DEFAULT_FROM_EMAIL = 'no-reply@motorpartexpress.com'

# Motor de envío (SMTP de Gmail para producción)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' #Para produccion

# Servidor SMTP de Gmail

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' #Prueba email desde consola para prueba 

# Servidor SMTP de Gmail
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587

# Credenciales (leídas del .env)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Configuración TLS (encriptación de la conexión)
EMAIL_USE_TLS = True #se usa para cifrar la conexión entre tu aplicación y el servidor de correo.
EMAIL_USE_SSL = False


#Para que Django sirva los archivos estáticos de manera eficiente en producción, especialmente cuando se utiliza un servidor web como Nginx o Apache.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'




